version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO 
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: info.log

loggers:
  tests:
    level: DEBUG
    handlers: [console,file]
    propagate: no

root:
  level: DEBUG
  handlers: [console,file]
